### ISSUE TITLE
tigervnc viewer running against UltraVNC server has an invisible cursor

### ISSUE THREAD

**Issue by ajschorr** [ultravnc/UltraVNC#24]
Hi,

There seems to be a buggy interaction between the Linux tigervnc viewer and UltraVNC server running on Windows 10 that results in an invisible cursor. The problem started with this tigervnc patch in December, 2019:

https://github.com/TigerVNC/tigervnc/commit/2cd3cb48164f105a1c066102c8430317d94bb9f0

I opened a TigerVNC bug about this here:

https://github.com/TigerVNC/tigervnc/issues/1335

However, they say that this is an UltraVNC server bug, although I do not have this problem with other
VNC clients such as RealVNC or vinagre or remmina. I have observed this problem at least since
UltraVNC server version 1.2.2.4. It is still present in 1.3.4.1.

I am not a VNC expert and do not know whether this is a bug in UltraVNC or TigerVNC or a combination thereof, but I would really appreciate a fix from one side or the other. The tigervnc client is the best solution on my linux platforms, as is UltraVNC server on my windows systems, but an invisible cursor is a disaster.

Thanks for your consideration,
Andy

**Comment by CendioOssman** [comment]
The issue is that if the client doesn't get a local cursor from the server then it has to assume it is an older type server that will render the cursor itself (e.g. those built in to some KVMs). Otherwise we'd end up with two cursors for the user (and the local would often be incorrect as well).

Hence it is crucial that UltraVNC sends the current cursor right away if it doesn't intend to render the cursor as part of the framebuffer.

**Comment by RudiDeVos** [comment]
Did a little research:
Seems TigerVNC send the pseudoEncoding before the actual encoding causing UltraVNC to ignore it.
Changed our code so that it's cached.
UltraVNC now end proper the cursor shapes.

TigerVNC support rfbEncodingXCursor/rfbEncodingRichCursor but not rfbEncodingPointerPos
The server can send the shapes, but can't send a position change, if the cursor moves on the server it isn't visible on the viewer as the move isn't supported.

**Comment by CendioOssman** [comment]
I don't think PointerPos is well supported (and it is also an extension, not a base feature). I would recommend rendering the cursor on the framebuffer for those clients. This is what the old, original code base from RealVNC did so it's somewhat the base behaviour.

**Comment by RudiDeVos** [comment]
Rendering the cursor on the framebuffer is the default behaviour when rfbEncodingXCursor/rfbEncodingRichCursor is not supported.  Then for the TigerVNC client i just ignore fbEncodingXCursor/rfbEncodingRichCursor support.

**Comment by ajschorr** [comment]
Thanks for researching this. I'm not sure I follow the discussion though. Has a patch to fix this been committed to UltraVNC? I don't see any recent commits. Sorry for my ignorance; I don't really understand the issues here, but I would like tigervnc viewer to work with UltraVNC server.

**Comment by RudiDeVos** [comment]
Yes, UltraVNC server is patches.
The UltraVNC pathed server  exe is available for download to do a fast test.
https://www.uvnc.eu/download/1342/winvnc_TigerCursorTest2.zip.

Just updated git (development branch)

**Comment by ajschorr** [comment]
Now I see it. Thank you.

**Comment by Neustradamus** [comment]
@ajschorr: Can you test your configuration with the latest build?

At this time, can you try the 1.8.0.5 release build?
- https://uvnc.eu/download/1800/UltraVNC_1805_x64_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1805_x86_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1805.zip

It works perfectly?
